# This file has mixed resources - some ArgoCD, some Kubernetes
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: production
data:
  app.env: production
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-api
  namespace: argocd
spec:
  project: backend
  source:
    repoURL: https://github.com/earthly/pantalasa-cronos
    targetRevision: HEAD
    path: backend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: backend-api
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: production
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080

